### PR TITLE
Make equality comparison of equivalent instances of `Term` return `True`

### PR DESCRIPTION
**Pull request by jonrkarr**
With Pronto 0.12.0, comparison of two instances of `Term` returns False even when the two instances have the same `id`. The pull request fixes this issue and adds a test case. The existing tests all still pass.
```
onto = pronto.Ontology('...')
term = onto['id']

onto_copy = pronto.Ontology('...')
term_copy = onto_copy['id']
term == term_copy --> False

term_copy = copy(term)
term == term_copy --> False
```

### CODE REVIEW

**Comment by althonos** [comment]
Couldn't there be an issue in the case the ontology is declared with a ` relax-unique-identifier-assumption-for-namespace` or such edge cases ?

**Comment by jonrkarr** [comment]
I didn't realize that ids don't have to be unique. In that case, I still think it would be helpful to have a function that checks semantic equality. Something like the following would be helpful, or is there already a method that does something like this?

```
class Ontology(collections.Mapping):
    ...
    
    def are_terms_equivalent(self, term_1, term_2):
        """ Determine if two terms are semantically equivalent

        Arguments:
            term_1 (:obj:`Term`): first term
            term_2 (:obj:`Term`): other term

        Returns:
            :obj:`bool`: :obj:`True` if the terms are the same
        """ 
        assert not self.meta.get('relax-unique-identifier-assumption', False)
        return term_1.id == term_2.id
```

**Comment by althonos** [comment]
Given Python is a language with reference-counting memory management, I'd find it less cumbersome to dynamically change the `__eq__` method of `Term` classes without having to refer back to the ontology by using a weakref.

I cannot guarantee this will get merged soon, but I'll be working a lot on `pronto` from March onwards as my Msc thesis, so hopefully I will end up with a nice solution to this problem.

(BTW the Whole-Cell project looks really nice and I'm always super-duper happy when people use my code ! :smile: )

**Comment by jonrkarr** [comment]
I think you're in the best position to decide how to implement `pronto`. Dynamically changing the `__eq__` method for subclasses of `Term` for specific ontologies would work well for us. A utility method that computes equality would also address our use case. For now, that's what we'll do so that we're using `pronto` consistently with the PyPI version.

**Comment by althonos** [comment]
@jonrkarr : actually, I'm stupid, ids have to be unique. 

However the Zen of Python states that *explicit is better than implicit*, so I'd be more in favor of having an `__eq__` implementation that compares **everything**: in your example that would still work because you're loading the same term twice so all its attributes should be equal. If you just wanted to compare ids, `term.id == term_copy.id` would work fine, and that's only a few extra letters.

**Comment by jonrkarr** [comment]
I think you were correct that the obo format allows for non-unique
namespaces. I wasn't aware of that. As a result, I learned that checking
ids isn't sufficient to check equality; all attributes need to be compared.
Implementing that would be useful to us.

After your earlier message, we switched to doing what you outlined,
checking the equality of ids.

**Comment by althonos** [comment]
In `pronto >= 1.0.0`, entity comparison is based on their identifier alone. Since two entities can only be equal if they share the same identifier, and since the `Ontology` object checks that no entities can have duplicate identifier, equality checking is done on the `id` field only.

**Comment by jonrkarr** [comment]
Thanks! We started using this a couple months ago.

**Pull request closed without merging**
