### PR TITLE
fix: accept XMLLiterals

### LINKED ISSUE #222: Error processing OWL
Thank you for pronto.

When I try to open https://data.bioontology.org/ontologies/HGNC/submissions/1/download, the following exception is thrown.
```
  File "/home/chris/.cache/pypoetry/virtualenvs/processed-open-ontologies-l-S_1ivg-py3.9/lib/python3.9/site-packages/pronto/ontology.py", line 283, in __init__
    cls(self).parse_from(_handle)  # type: ignore

  File "/home/chris/.cache/pypoetry/virtualenvs/processed-open-ontologies-l-S_1ivg-py3.9/lib/python3.9/site-packages/pronto/parsers/rdfxml.py", line 117, in parse_from
    self._extract_term(class_, curies)

  File "/home/chris/.cache/pypoetry/virtualenvs/processed-open-ontologies-l-S_1ivg-py3.9/lib/python3.9/site-packages/pronto/parsers/rdfxml.py", line 449, in _extract_term
    termdata.annotations.add(self._extract_literal_pv(child))

  File "/home/chris/.cache/pypoetry/virtualenvs/processed-open-ontologies-l-S_1ivg-py3.9/lib/python3.9/site-packages/pronto/parsers/rdfxml.py", line 239, in _extract_literal_pv
    property, typing.cast(str, elem.text), self._compact_datatype(datatype)

  File "/home/chris/.cache/pypoetry/virtualenvs/processed-open-ontologies-l-S_1ivg-py3.9/lib/python3.9/site-packages/pronto/parsers/rdfxml.py", line 185, in _compact_datatype
    raise iri
```
When I replace the line with `raise ValueError(iri)` the exception is:
```
ValueError: http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral
```

If I add:
```        match = re.match("^http://www.w3.org/1999/02/22-rdf-syntax-ns#(.*)", iri)
        if match is not None:
            return f"rdf:{match.group(1)}"
```
Then processing appears successful.

### PR DESCRIPTION
**Pull request by chrishmorris**
Fixes #222

### CODE REVIEW

**Comment by althonos** [comment]
Hi @chrishmorris, thanks for the PR! I think you changed the wrong method here, you need to patch `_compact_datatype` and not `_compact_id`, unless I'm wrong?

**Comment by chrishmorris** [comment]
Yes you are correct, thank you.

I will correct this when I can - sorry, I have a crunch in the day job just now.

**Comment by althonos** [comment]
No problem, just ping me when that's fixed :wink:

**Comment by chrishmorris** [comment]
Fixed now, it would be great if you decide to adopt this fix. Thank you for Pronto.

**Pull request merged**
